#!/bin/bash
#
# Link all the scripts here to ~/bin/

DIRNAME=$(realpath $(dirname $0))

for script in $DIRNAME/*.sh; do
    echo linking $script to ~/bin/$(basename $script)
    ln -s $script ~/bin/$(basename $script)
done
